# Generated by Django 3.2.9 on 2022-08-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone1',
            field=models.CharField(default='+254', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=models.CharField(default='+254', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_number',
            field=models.IntegerField(unique=True),
        ),
    ]
